[package]
name = "db_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.41"
mockall = "0.13.0"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "sqlite"] }
structopt = "0.3"
tokio = { version = "1.3", features = ["macros"] }
